// org-data.jsx — the OpenMake organisation's dataset. Loaded BEFORE
// landing-data.jsx, which builds the account-switchable data from these
// configs (window.applyAccountData). Same shapes as the personal data,
// just an order of magnitude more of it, and much more frequent — a
// company workspace, not a personal one.

// ── Repositories ────────────────────────────────────────────────
const ORG_REPO_DEFS = {
  "openmake/forge": {
    ns: "OpenMake", nm: "forge",
    description: "Core orchestration platform — schedules agent runs, leases boxes, and freezes run records for every job.",
    default_branch: "main",
    open_traces: 14, total_traces: 186, contributors: 34,
    last_push: "4 min ago",
    workflows: ["wf-eval-suite", "wf-shortcut-redesign", "wf-doc-extract"],
    datasets: ["ds-agent-sessions-prod", "ds-release-gates"],
    working_tree: { modified: 6, added: 2, deleted: 1, current_trace: { id: "b12·40c8e", title: "Lease scheduler backpressure fix" } },
  },
  "openmake/console": {
    ns: "OpenMake", nm: "console",
    description: "The web console — projects, traces, datasets, and billing surfaces for every workspace.",
    default_branch: "main",
    open_traces: 8, total_traces: 142, contributors: 18,
    last_push: "22 min ago",
    workflows: ["wf-rag-grader"],
    datasets: ["ds-support-triage-evals"],
    working_tree: { modified: 3, added: 0, deleted: 0, current_trace: { id: "c88·1f02a", title: "Usage page: hourly metering rollup" } },
  },
  "openmake/relay": {
    ns: "OpenMake", nm: "relay",
    description: "Event gateway — ingests trace events at the edge and fans out to buckets, datasets, and webhooks.",
    default_branch: "main",
    open_traces: 5, total_traces: 118, contributors: 12,
    last_push: "1h ago",
    workflows: ["wf-nightly-bench"],
    datasets: ["ds-latency-matrix", "ds-red-team-suite"],
    working_tree: { modified: 0, added: 0, deleted: 0, current_trace: null },
  },
  "openmake/schemas": {
    ns: "OpenMake", nm: "schemas",
    description: "Shared schema registry — versioned record shapes every service and SDK compiles against.",
    default_branch: "main",
    open_traces: 2, total_traces: 64, contributors: 21,
    last_push: "3h ago",
    workflows: ["wf-shortcut-redesign"],
    datasets: ["ds-release-gates"],
    working_tree: { modified: 1, added: 0, deleted: 0, current_trace: { id: "d02·9ac11", title: "run_record v1 → v2 migration shim" } },
  },
  "openmake/sdk-python": {
    ns: "OpenMake", nm: "sdk-python",
    description: "Python SDK — capture, query, and replay traces from any harness.",
    default_branch: "main",
    open_traces: 3, total_traces: 87, contributors: 9,
    last_push: "38 min ago",
    workflows: ["wf-nightly-bench"],
    datasets: ["ds-latency-matrix"],
    working_tree: { modified: 0, added: 0, deleted: 0, current_trace: null },
  },
  "openmake/sdk-js": {
    ns: "OpenMake", nm: "sdk-js",
    description: "TypeScript SDK + browser capture shim for web-embedded agents.",
    default_branch: "main",
    open_traces: 4, total_traces: 92, contributors: 11,
    last_push: "51 min ago",
    workflows: [],
    datasets: [],
    working_tree: { modified: 2, added: 1, deleted: 0, current_trace: { id: "e71·33b90", title: "Streaming capture for web workers" } },
  },
  "openmake/docs": {
    ns: "OpenMake", nm: "docs",
    description: "Product docs, guides, and the public changelog — doc-extract keeps it in lockstep with the code.",
    default_branch: "main",
    open_traces: 1, total_traces: 58, contributors: 26,
    last_push: "2h ago",
    workflows: ["wf-doc-extract"],
    datasets: [],
    working_tree: { modified: 0, added: 0, deleted: 0, current_trace: null },
  },
  "openmake/infra": {
    ns: "OpenMake", nm: "infra",
    description: "Terraform + k8s manifests for every environment — box fleets, buckets, and the metering pipeline.",
    default_branch: "main",
    open_traces: 2, total_traces: 73, contributors: 8,
    last_push: "5h ago",
    workflows: [],
    datasets: [],
    working_tree: { modified: 0, added: 0, deleted: 0, current_trace: null },
  },
  "openmake/billing-engine": {
    ns: "OpenMake", nm: "billing-engine",
    description: "Hourly metering and invoicing — turns box-lease hours per environment into line items.",
    default_branch: "main",
    open_traces: 1, total_traces: 49, contributors: 7,
    last_push: "26 min ago",
    workflows: ["wf-eval-suite"],
    datasets: ["ds-red-team-suite"],
    working_tree: { modified: 4, added: 0, deleted: 2, current_trace: { id: "f19·77d03", title: "Proration for mid-hour reaps" } },
  },
};

// ── Datasets ────────────────────────────────────────────────────
const ORG_DATASET_DEFS = {
  "ds-agent-sessions-prod": {
    name: "agent-sessions-prod",
    description: "Every production agent session, scrubbed and normalised — the company's primary corpus.",
    rows: 184206, cols: 9,
    workflow: "wf-eval-suite", workflow_label: "release-evals",
    remote: "ahead", remote_kind: "hf",
    remote_repo: "openmake/agent-sessions-prod",
    remote_url: "https://huggingface.co/datasets/openmake/agent-sessions-prod",
    auto_policy: false,
    inbox_count: 43, staging_count: 12,
    last_run: "18 min ago", last_update: "18 min ago",
    pending_push: 9, local_commits: 214, remote_commits: 205,
    sample_columns: ["session_id", "surface", "agent", "turns", "outcome", "cost_usd", "duration_s", "tokens", "flags"],
    sample_rows: [
      ["s.88f102", "forge/scheduler", "Claude Code", 31, "merged", 4.12, 1840, 88410, ""],
      ["s.88f0e7", "console/usage", "Cursor", 12, "committed", 1.08, 622, 21050, ""],
      ["s.88f0c3", "relay/ingest", "Codex", 54, "failed", 7.91, 3320, 152800, "tool-thrash"],
      ["s.88f0a9", "sdk-js/capture", "Claude Code", 9, "pushed", 0.64, 410, 12240, ""],
    ],
  },
  "ds-support-triage-evals": {
    name: "support-triage-evals",
    description: "Graded triage decisions from the support copilot — judged weekly against the answer key.",
    rows: 48112, cols: 7,
    workflow: "wf-rag-grader", workflow_label: "support-rag-grader",
    remote: "synced", remote_kind: "hf",
    remote_repo: "openmake/support-triage-evals",
    remote_url: "https://huggingface.co/datasets/openmake/support-triage-evals",
    auto_policy: false,
    inbox_count: 7, staging_count: 2,
    last_run: "2h ago", last_update: "2h ago",
    pending_push: 0, local_commits: 96, remote_commits: 96,
    sample_columns: ["ticket_id", "intent", "routed_to", "expected", "score", "judge_notes", "latency_ms"],
    sample_rows: [
      ["t.40412", "billing-dispute", "billing/tier-2", "billing/tier-2", 1.00, "exact", 810],
      ["t.40413", "sdk-install-fail", "eng/sdk", "eng/sdk", 0.94, "right queue, partial context", 1120],
      ["t.40414", "quota-increase", "billing/tier-1", "sales", 0.31, "misrouted — revenue intent missed", 940],
    ],
  },
  "ds-release-gates": {
    name: "release-gates",
    description: "Every gate check from every release train — verdicts, blockers, and overrides.",
    rows: 9314, cols: 6,
    workflow: "wf-shortcut-redesign", workflow_label: "release-gate-sweep",
    remote: "synced", remote_kind: "hf",
    remote_repo: "openmake/release-gates",
    remote_url: "https://huggingface.co/datasets/openmake/release-gates",
    auto_policy: true,
    inbox_count: 0, staging_count: 0,
    last_run: "55 min ago", last_update: "55 min ago",
    pending_push: 0, local_commits: 402, remote_commits: 402,
    sample_columns: ["train", "gate", "verdict", "blocker", "owner", "overridden"],
    sample_rows: [
      ["forge-2.9", "bench-green", "pass", "", "@mira", "no"],
      ["forge-2.9", "atlas-fresh", "pass", "", "@mira", "no"],
      ["console-1.14", "red-team", "fail", "prompt-injection regression", "@tomas", "no"],
    ],
  },
  "ds-latency-matrix": {
    name: "latency-matrix",
    description: "Nightly latency + throughput sweep across the model × region matrix.",
    rows: 22540, cols: 6,
    workflow: "wf-nightly-bench", workflow_label: "nightly-bench",
    remote: "synced", remote_kind: "hf",
    remote_repo: "openmake/latency-matrix",
    remote_url: "https://huggingface.co/datasets/openmake/latency-matrix",
    auto_policy: true,
    inbox_count: 0, staging_count: 0,
    last_run: "6h ago", last_update: "6h ago",
    pending_push: 0, local_commits: 188, remote_commits: 188,
    sample_columns: ["model", "region", "p50_ms", "p99_ms", "tok_per_s", "errors"],
    sample_rows: [
      ["sonnet-4.5", "us-east", 420, 1180, 96, 0],
      ["sonnet-4.5", "eu-west", 465, 1310, 91, 0],
      ["gpt-5.3", "us-east", 510, 1640, 84, 2],
    ],
  },
  "ds-red-team-suite": {
    name: "red-team-suite",
    description: "Adversarial prompts + expected refusals for the release red-team gate.",
    rows: 3871, cols: 5,
    workflow: "wf-rag-grader", workflow_label: "support-rag-grader",
    remote: "behind", remote_kind: "hf",
    remote_repo: "openmake/red-team-suite",
    remote_url: "https://huggingface.co/datasets/openmake/red-team-suite",
    auto_policy: false,
    inbox_count: 11, staging_count: 0,
    last_run: "yesterday", last_update: "yesterday",
    pending_push: 0, local_commits: 41, remote_commits: 44,
    sample_columns: ["probe_id", "category", "expected", "observed", "verdict"],
    sample_rows: [
      ["p.0091", "prompt-injection", "refuse + report", "refuse + report", "pass"],
      ["p.0092", "data-exfil", "refuse", "partial completion", "fail"],
      ["p.0093", "privilege-escalation", "refuse", "refuse", "pass"],
    ],
  },
};

// ── Workflows (same ids as personal — pages resolve by id) ──────
const ORG_WORKFLOW_DEFS = {
  "wf-eval-suite": {
    name: "release-evals",
    description: "Company-wide regression evals against the latest snapshot of every production agent surface.",
    instructions: "# release-evals\n\n1. Pull fixtures from `openmake/forge:fixtures/eval/`.\n2. Sweep every production surface with deterministic seeds.\n3. Score against the golden set; emit deltas per surface.\n4. Append rows to `agent-sessions-prod`.",
    schedule: "Every 6h",
    lastFired: "18 min ago", nextFire: "in 5h",
    triggers: ["schedule", "manual", "release train"],
    producedDatasets: ["agent-sessions-prod"],
  },
  "wf-nightly-bench": {
    name: "nightly-bench",
    description: "Latency and throughput benchmarks across the model × region matrix.",
    instructions: "# nightly-bench\n\n1. Spin up isolated runners per model × region.\n2. Fixed prompt sequence, cold + warm passes.\n3. Capture p50/p99 latency, throughput, error rate.\n4. Append to `latency-matrix`.",
    schedule: "Nightly at 03:00 UTC",
    lastFired: "6h ago", nextFire: "in 18h",
    triggers: ["schedule"],
    producedDatasets: ["latency-matrix"],
  },
  "wf-rag-grader": {
    name: "support-rag-grader",
    description: "Grades the support copilot's triage decisions and retrieval citations against the curated answer key.",
    instructions: "# support-rag-grader\n\n1. Load `support-triage-evals` (tickets + answer key).\n2. Replay each ticket through the copilot under test.\n3. Judge routing precision + citation faithfulness.\n4. Emit per-ticket scores and an aggregate report.",
    schedule: "Weekly + on PR",
    lastFired: "2h ago", nextFire: "in 5 days",
    triggers: ["schedule", "PR open", "manual"],
    producedDatasets: ["support-triage-evals", "red-team-suite"],
  },
  "wf-shortcut-redesign": {
    name: "release-gate-sweep",
    description: "Runs every gate on the active release trains and freezes verdicts into the gate ledger.",
    instructions: "# release-gate-sweep\n\n1. Enumerate active release trains.\n2. Run bench-green, atlas-fresh, and red-team gates per train.\n3. Freeze verdicts + blockers into `release-gates`.",
    schedule: "Hourly during trains",
    lastFired: "55 min ago", nextFire: "in 5 min",
    triggers: ["schedule", "manual"],
    producedDatasets: ["release-gates"],
  },
  "wf-doc-extract": {
    name: "doc-extract",
    description: "Detects merged changes and propagates doc updates across the docs repo and public changelog.",
    instructions: "# doc-extract\n\n1. Compare HEAD against the last doc-sync commit.\n2. Map changed surfaces to doc files.\n3. Draft edits as a unified diff for review in `openmake/docs`.",
    schedule: "On merge to main",
    lastFired: "9 min ago", nextFire: null,
    triggers: ["webhook", "manual"],
    producedDatasets: [],
  },
};

// ── Trace generation config ─────────────────────────────────────
const ORG_TRACE_TITLES = [
  "Lease scheduler backpressure fix",
  "Usage page: hourly metering rollup",
  "Proration for mid-hour reaps",
  "run_record v1 → v2 migration shim",
  "Streaming capture for web workers",
  "Relay ingest: dedupe window widened",
  "Forge 2.9 release train prep",
  "Red-team gate: injection regression",
  "Support copilot routing pass",
  "SDK retry semantics unified",
  "Region failover drill artifacts",
  "Gate ledger export to HF",
  "Console dark-mode contrast sweep",
  "Billing meter drift investigation",
  "Schema registry breaking-change lint",
  "Docs sync for capture API",
  "Latency matrix: eu-west regression",
  "Box fleet autoscaler tuning",
  "Bucket compaction for old traces",
  "Webhook fanout at-least-once fix",
  "Terraform drift on metering pipeline",
  "Answer key refresh for triage evals",
  "Changelog automation follow-up",
  "Sonnet snapshot bump + eval sweep",
];
const ORG_DATASET_BY_REPO = {
  "openmake/forge": ["agent-sessions-prod", "release-gates"],
  "openmake/console": ["support-triage-evals"],
  "openmake/relay": ["latency-matrix", "red-team-suite"],
  "openmake/schemas": ["release-gates"],
  "openmake/sdk-python": ["latency-matrix"],
  "openmake/sdk-js": [],
  "openmake/docs": [],
  "openmake/infra": [],
  "openmake/billing-engine": ["red-team-suite"],
};

// ── Colors (merged into the shared color maps) ──────────────────
const ORG_REPO_COLORS = {
  "openmake/forge":          "var(--c-write)",
  "openmake/console":        "var(--c-read)",
  "openmake/relay":          "var(--c-exec)",
  "openmake/schemas":        "var(--c-plan)",
  "openmake/sdk-python":     "var(--c-git)",
  "openmake/sdk-js":         "var(--c-user)",
  "openmake/docs":           "var(--c-push)",
  "openmake/infra":          "var(--c-think)",
  "openmake/billing-engine": "var(--c-error)",
};
const ORG_DATASET_COLORS = {
  "agent-sessions-prod":  "var(--c-write)",
  "support-triage-evals": "var(--c-read)",
  "release-gates":        "var(--c-plan)",
  "latency-matrix":       "var(--c-user)",
  "red-team-suite":       "var(--c-exec)",
};

// ── Overview projects strip ─────────────────────────────────────
const ORG_OV2_PROJECTS = [
  { id: "openmake/forge",          bench: { pass: 41, fail: 3, when: "35m" }, atlas: { fresh: 14, total: 16 }, evidence: { n: 128, unread: 9 } },
  { id: "openmake/console",        bench: { pass: 34, fail: 2, when: "2h" },  atlas: { fresh: 11, total: 12 }, evidence: { n: 96,  unread: 4 } },
  { id: "openmake/relay",          bench: { pass: 21, fail: 1, when: "5h" },  atlas: { fresh: 8,  total: 9 },  evidence: { n: 61,  unread: 0 } },
  { id: "openmake/sdk-js",         bench: { pass: 17, fail: 3, when: "1h" },  atlas: { fresh: 5,  total: 8 },  evidence: { n: 44,  unread: 7 } },
  { id: "openmake/billing-engine", bench: { pass: 12, fail: 0, when: "40m" }, atlas: { fresh: 6,  total: 6 },  evidence: { n: 28,  unread: 1 } },
];

const ORG_TOP_AGENTS = [
  { name: "Claude Code", count: 1204, icon: "claude" },
  { name: "Cursor", count: 861, icon: "cursor" },
  { name: "Codex", count: 512, icon: "codex" },
  { name: "Gemini CLI", count: 238, icon: "gemini" },
];

Object.assign(window, {
  ORG_REPO_DEFS, ORG_DATASET_DEFS, ORG_WORKFLOW_DEFS,
  ORG_TRACE_TITLES, ORG_DATASET_BY_REPO,
  ORG_REPO_COLORS, ORG_DATASET_COLORS,
  ORG_OV2_PROJECTS, ORG_TOP_AGENTS,
});
