from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXAMPLES = ROOT / "examples"

PUBLIC_EXAMPLES = {
    "standup": "turn sanitized bucket-session summaries into a narrative",
    "trace-capsule": "bounded, redacted trace episode",
    "intent-pr": "ties branch commits back to originating sessions",
    "spotlight": "bounded trace-search packet",
    "skill-evaluation": "synthetic verifier-candidate packet",
    "trace-intelligence/eval": "synthetic labeled evaluation packet",
}


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def read_json(path: Path) -> dict:
    return json.loads(read_text(path))


def normalized(text: str) -> str:
    return " ".join(text.split())


def test_examples_index_lists_each_public_example():
    index = read_text(EXAMPLES / "README.md")
    flat_index = normalized(index)

    assert "`examples/` is the only public examples/demo folder" in index
    for example, purpose in PUBLIC_EXAMPLES.items():
        assert f"`{example}/`" in index
        assert purpose in flat_index


def test_each_public_example_has_task_contract():
    private_markers = [
        "/" + "Users/",
        "OPENAI" + "_API_KEY",
        "ANTHROPIC" + "_API_KEY",
        "GITHUB" + "_TO" + "KEN",
        "ghp_",
        "hf_",
        "sk-",
    ]

    for example in PUBLIC_EXAMPLES:
        readme = read_text(EXAMPLES / example / "README.md")

        assert "## Task" in readme, example
        assert "## Inputs" in readme, example
        assert ("## Run" in readme or "## Expected Output" in readme), example
        for marker in private_markers:
            assert marker not in readme, f"{example} contains private marker {marker}"


def test_public_examples_do_not_use_stale_cli_forms():
    combined = "\n".join(
        path.read_text(encoding="utf-8")
        for path in sorted(EXAMPLES.rglob("*"))
        if path.is_file()
    )

    stale_forms = [
        "--ski" + "ll review",
        "--" + "pr 123",
        "--re" + "po owner/project",
        "workflow create --temp" + "late",
        "runs/standup" + "-demo",
        "examples/skill" + "-intelligence",
        "de" + "mos/",
    ]
    for form in stale_forms:
        assert form not in combined


def test_trace_capsule_example_is_capsule_task():
    readme = read_text(EXAMPLES / "trace-capsule" / "README.md")
    capsule_path = EXAMPLES / "trace-capsule" / "capsule.sample.json"
    capsule = read_json(capsule_path)

    assert capsule["schema_version"] == "opentraces.capsule.v1"
    assert capsule["content_is_untrusted"] is True
    assert capsule["source"]["trace_id"] == "trace-example-capsule"
    assert capsule["summary"]["is_failure"] is True
    assert capsule["privacy_scope"]["system_prompt_included"] is False
    assert capsule["privacy_scope"]["reasoning_included"] is False
    assert capsule["test"]["expected"]["kind"] == "error_string"
    assert capsule["redaction"]["manifest"]["floor_satisfied"] is True
    assert capsule["redaction"]["manifest"]["floor"] == ["regex", "entropy", "business_logic"]
    assert "pytest tests/test_duration_parser.py::test_accepts_iso_duration" in capsule["test"]["command"]
    assert "opentraces capsule preview" in readme
    assert "opentraces capsule get" in readme
    assert "--issue-repo owner/project" in readme
    assert "--json > capsule.json" in readme
    assert "GitHub issue" in readme

    proc = subprocess.run(
        [
            sys.executable,
            "-c",
            "from opentraces.cli import main; main()",
            "capsule",
            "open",
            str(capsule_path),
            "--json",
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
        timeout=10,
    )
    assert proc.returncode == 0, proc.stderr
    opened = json.loads(proc.stdout)
    assert opened["capsule_id"] == capsule["capsule_id"]


def test_intent_pr_example_is_pr_report_task():
    readme = read_text(EXAMPLES / "intent-pr" / "README.md")
    report = read_text(EXAMPLES / "intent-pr" / "sample-pr-report.md")

    assert "opentraces trail blame pr render --base main --no-llm" in readme
    assert "opentraces trail blame pr create --base main --no-llm" in readme
    assert "opentraces trail blame pr update --base main --number 123 --no-llm" in readme
    assert "Generated by `opentraces trail blame pr render --base main --no-llm`" in report
    assert "## Intent" in report
    assert "## Trace evidence" in report
    assert "## Review notes" in report
    assert "originating session" in readme


def test_spotlight_example_is_bounded_search_task():
    readme = read_text(EXAMPLES / "spotlight" / "README.md")
    packet = read_json(EXAMPLES / "spotlight" / "candidate-packet.sample.json")

    assert packet["schema_version"] == "opentraces.candidate_packet.v1"
    assert packet["total_returned"] == len(packet["candidates"])
    for candidate in packet["candidates"]:
        assert candidate["trace_id"]
        assert candidate["unit_id"].startswith("tu:")
        assert candidate["headline"]
        assert candidate["why"]
    assert "opentraces trace query" in readme
    assert "opentraces trace map" in readme
    assert "opentraces trace slice" in readme
    assert "candidate-packet.sample.json" in readme
    assert "not a full transcript dump" in readme


def test_skill_evaluation_example_is_synthetic_verifier_task():
    readme = read_text(EXAMPLES / "skill-evaluation" / "README.md")
    packet = read_json(EXAMPLES / "skill-evaluation" / "skill-verifier-candidate.sample.json")

    assert packet["schema_version"] == "opentraces.skill_verifier_candidates.v1"
    assert packet["project"] == "example-public-fixture"
    assert packet["skills"][0]["skill_id"] == "review"
    assert packet["skills"][0]["sources"] == ["synthetic-public-example"]
    assert packet["skills"][0]["archetypes"][0]["provenance"]["privacy"] == "synthetic"
    assert packet["skills"][0]["leakage_safe_split"] is True
    assert "skill-verifier-candidates-v1" in readme
    assert "opentraces workflow create skill-verifier-candidates-example --template skill-verifier-candidates-v1 --json" in readme
    assert "opentraces skill-verifier status review --json" in readme
    assert "not a calibrated verifier" in normalized(readme)
    assert "does not claim a pass verdict" in readme


def test_standup_example_prompt_accepts_pr_reports_and_capsules():
    prompt = read_text(EXAMPLES / "standup" / "STANDUP-PROMPT.md")
    readme = read_text(EXAMPLES / "standup" / "README.md")
    packet = read_text(EXAMPLES / "standup" / "sample-evidence-packet.md")
    sample = read_text(EXAMPLES / "standup" / "sample-standup.md")

    assert "trace capsules" in prompt
    assert "pull request reports" in prompt
    assert "{{evidence_packet}}" in prompt
    assert "## Standup-ready" in prompt
    assert "Trace capsules" in readme
    assert "Pull request reports" in readme
    assert "sample-evidence-packet.md" in readme
    assert "Narrative Session Summary" in packet
    assert "Trace Capsule" in packet
    assert "Pull Request Report" in packet
    assert "## Standup-ready" in sample
    assert "not be described as merged" in packet


def test_trace_intelligence_eval_example_scorecard_matches_packet():
    scorecard = read_json(EXAMPLES / "trace-intelligence" / "eval" / "scorecard.json")
    rows = [
        json.loads(line)
        for line in read_text(EXAMPLES / "trace-intelligence" / "eval" / "run-intelligence-eval.jsonl").splitlines()
        if line.strip()
    ]
    readme = read_text(EXAMPLES / "trace-intelligence" / "eval" / "README.md")

    assert scorecard["dataset_rows"] == len(rows)
    assert scorecard["context_waste"]["f1"] == 1.0
    assert scorecard["run_intel"]["f1"] == 0.933
    assert scorecard["run_intel"]["fn"] == 1
    assert "adv-recover-novocab" in readme
    assert "opentraces trace get <trace-id> --waste --json" in readme
    assert "opentraces trace compare <trace-a> <trace-b> --json" in readme
