"""Self-contained deterministic scorer for verifier package docs_update_reflects_change_v1.

Generated by the OpenTraces Skill Verifier Factory. No imports beyond stdlib; safe
to run in default CI. Scores a candidate skill by the fraction of this archetype's
trace-grounded rule markers it addresses. Live/semantic legs are declared in
spec.yaml and are opt-in (never invoked here).
"""

from __future__ import annotations

ARCHETYPE_ID = 'docs_update_reflects_change_v1'
SKILL_ID = 'docs-update'
MARKERS = ['rl.docs-update.changelog', 'rl.docs-update.no_stale']


def _marker_token(tag: str) -> str:
    return "rule[" + tag + "]"


def score_skill(skill_text: str) -> float:
    """Fraction of this archetype's markers the skill text addresses, in [0,1]."""
    if not MARKERS:
        return 0.0
    hit = sum(1 for m in MARKERS if _marker_token(m) in skill_text)
    return round(hit / len(MARKERS), 6)


if __name__ == "__main__":  # pragma: no cover
    import sys

    text = ""
    if len(sys.argv) > 1:
        with open(sys.argv[1], "r", encoding="utf-8") as fh:
            text = fh.read()
    print(score_skill(text))
