"""Parser handling of compaction artifacts.

A /compact operation produces two synthetic JSONL lines written in place:
  1. ``{type: system, subtype: compact_boundary}``
  2. ``{type: user, isCompactSummary: true}`` — Claude Code's auto-generated
     summary of the pre-boundary history, which the agent reads on
     subsequent turns instead of the full transcript.

The original pre-compact turns remain in the file above the boundary.
Our parser re-derives from offset 0 on every ingest, so it already has
the full uncompacted history; the synthetic summary adds no information
and pollutes the trace with content the user never typed. Skip it.

The ``compact_boundary`` marker is still consumed (flips
``metadata.is_compacted = True``) — that signal is useful for dataset
consumers.
"""

from __future__ import annotations

import json
from pathlib import Path

from opentraces.capture.claude_code.parse import ClaudeCodeParser


def _write(tmp_path: Path, lines: list[dict], name: str = "compact.jsonl") -> Path:
    p = tmp_path / name
    with p.open("w") as f:
        for line in lines:
            f.write(json.dumps(line) + "\n")
    return p


def _user_turn(ts: str, text: str, *, extra: dict | None = None) -> dict:
    line = {
        "type": "user",
        "sessionId": "compact-sess",
        "timestamp": ts,
        "message": {"role": "user", "content": text},
    }
    if extra:
        line.update(extra)
    return line


def _assistant_tool_turn(ts: str, tool_id: str, tool_name: str = "Read") -> dict:
    return {
        "type": "assistant",
        "sessionId": "compact-sess",
        "timestamp": ts,
        "message": {
            "role": "assistant",
            "content": [
                {"type": "tool_use", "id": tool_id, "name": tool_name,
                 "input": {"file_path": "x.py"}},
            ],
            "usage": {"input_tokens": 10, "output_tokens": 10},
        },
    }


def _tool_result(ts: str, tool_id: str, content: str = "ok") -> dict:
    return {
        "type": "user",
        "sessionId": "compact-sess",
        "timestamp": ts,
        "message": {
            "role": "user",
            "content": [
                {"type": "tool_result", "tool_use_id": tool_id, "content": content},
            ],
        },
    }


def _compact_boundary(ts: str) -> dict:
    return {
        "type": "system",
        "subtype": "compact_boundary",
        "sessionId": "compact-sess",
        "timestamp": ts,
        "compact_metadata": {"trigger": "user"},
        "pre_tokens": 50000,
    }


def _synthetic_summary(ts: str, text: str = "Prior session summary") -> dict:
    """The line Claude Code writes immediately after compact_boundary."""
    return {
        "type": "user",
        "sessionId": "compact-sess",
        "timestamp": ts,
        "isCompactSummary": True,
        "message": {"role": "user", "content": text},
    }


def test_parser_skips_compact_summary_user_line(tmp_path: Path) -> None:
    """isCompactSummary=true user lines must not become user steps in the trace."""
    lines = [
        _user_turn("2026-04-15T07:00:00Z", "please fix the bug"),
        _assistant_tool_turn("2026-04-15T07:00:01Z", "tu_1"),
        _tool_result("2026-04-15T07:00:02Z", "tu_1"),
        _compact_boundary("2026-04-15T07:10:00Z"),
        _synthetic_summary("2026-04-15T07:10:00Z",
                           "auto-generated summary the user never typed"),
        _user_turn("2026-04-15T07:11:00Z", "now do the other thing"),
        _assistant_tool_turn("2026-04-15T07:11:01Z", "tu_2"),
        _tool_result("2026-04-15T07:11:02Z", "tu_2"),
    ]
    session_path = _write(tmp_path, lines)

    record = ClaudeCodeParser().parse_session(session_path)

    assert record is not None

    user_texts = [
        step.content or ""
        for step in record.steps
        if step.role == "user"
    ]

    pre_compact = any("please fix the bug" in t for t in user_texts)
    post_compact = any("now do the other thing" in t for t in user_texts)
    synthetic = any("auto-generated summary" in t for t in user_texts)

    assert pre_compact, "pre-compact real user turn must survive"
    assert post_compact, "post-compact real user turn must survive"
    assert not synthetic, (
        "synthetic isCompactSummary user line must NOT appear as a user step "
        "(it is auto-generated by Claude Code, not typed by the human)"
    )


def test_parser_still_flags_is_compacted(tmp_path: Path) -> None:
    """Skipping the synthetic summary must not lose the is_compacted signal.

    The compact_boundary marker carries that signal independently.
    """
    lines = [
        _user_turn("2026-04-15T07:00:00Z", "do thing"),
        _assistant_tool_turn("2026-04-15T07:00:01Z", "tu_1"),
        _tool_result("2026-04-15T07:00:02Z", "tu_1"),
        _compact_boundary("2026-04-15T07:10:00Z"),
        _synthetic_summary("2026-04-15T07:10:00Z"),
        _user_turn("2026-04-15T07:11:00Z", "continue"),
        _assistant_tool_turn("2026-04-15T07:11:01Z", "tu_2"),
        _tool_result("2026-04-15T07:11:02Z", "tu_2"),
    ]
    session_path = _write(tmp_path, lines)

    record = ClaudeCodeParser().parse_session(session_path)

    assert record is not None
    assert record.metadata.get("is_compacted") is True, (
        "compact_boundary marker must still set is_compacted=True"
    )
