"""opentraces-schema: Pydantic models for the opentraces.ai JSONL trace format."""

from .models import (
    Agent,
    Attribution,
    AttributionConversation,
    AttributionFile,
    AttributionRange,
    Environment,
    GitLink,
    Metrics,
    Observation,
    Outcome,
    SecurityMetadata,
    Snippet,
    Step,
    Task,
    TokenUsage,
    ToolCall,
    TraceRecord,
    VCS,
)
from .trace_index import (
    CandidatePacket,
    TraceFacet,
    TraceMap,
    TraceMapEdge,
    TraceMapNode,
    TraceSignal,
    TraceUnit,
)
from .version import SCHEMA_VERSION

__all__ = [
    "Agent",
    "Attribution",
    "AttributionConversation",
    "AttributionFile",
    "AttributionRange",
    "CandidatePacket",
    "Environment",
    "GitLink",
    "Metrics",
    "Observation",
    "Outcome",
    "SCHEMA_VERSION",
    "SecurityMetadata",
    "Snippet",
    "Step",
    "Task",
    "TokenUsage",
    "ToolCall",
    "TraceFacet",
    "TraceMap",
    "TraceMapEdge",
    "TraceMapNode",
    "TraceRecord",
    "TraceSignal",
    "TraceUnit",
    "VCS",
]
