"""Deterministic, trace-grounded scorers for verifier archetypes.

These are the CI-safe heart of every verifier package: no network, no live agent,
fully deterministic. Two complementary surfaces:

* **episode scoring** (:func:`score_episode`) reads a captured ``skill-episodes-v1``
  row and reports which contract elements the trace exhibits, which markers are
  therefore *deficient* (the failure tags the optimizer must address), and the
  trace's own outcome reward. This is the label-free signal mined from real work.
* **skill scoring** (:func:`score_skill`) reports the fraction of an archetype's
  markers a candidate skill text addresses. This rides the proven SkillOpt marker
  mechanism and is what the Dsel/Dtest gate measures.

The shipped per-package ``scorer.py`` is generated from these functions so a
package is self-describing and re-runnable in isolation.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from ..skill_opt.engine import RULE_MARKER
from .archetypes import VerifierArchetype, evidence_from_episode


@dataclass(frozen=True)
class EpisodeScore:
    """The deterministic verdict for one episode under one archetype."""

    present_markers: tuple[str, ...]
    deficient_markers: tuple[str, ...]
    outcome_reward: float
    contract_completeness: float  # weighted fraction of elements present
    signals: dict[str, bool]


def score_episode(
    archetype: VerifierArchetype, episode: dict[str, Any], record: Any = None
) -> EpisodeScore:
    """Detect archetype contract elements in a captured episode (label-free).

    ``record`` is the optional source ``TraceRecord``; when supplied the evidence is
    enriched with the real shell commands + commit signal (Codex exec_command opacity).
    """
    evidence = evidence_from_episode(episode, record)
    present: list[str] = []
    deficient: list[str] = []
    signals: dict[str, bool] = {}
    total_w = 0.0
    present_w = 0.0
    for element in archetype.contract_elements:
        ok = bool(element.detect(evidence))
        signals[element.element_id] = ok
        total_w += element.weight
        if ok:
            present.append(element.marker)
            present_w += element.weight
        else:
            deficient.append(element.marker)
    completeness = round(present_w / total_w, 6) if total_w else 0.0
    return EpisodeScore(
        present_markers=tuple(present),
        deficient_markers=tuple(deficient),
        outcome_reward=evidence.outcome_reward,
        contract_completeness=completeness,
        signals=signals,
    )


def score_skill(archetype: VerifierArchetype, skill_text: str) -> float:
    """Fraction of an archetype's markers a candidate skill text addresses [0,1]."""
    markers = archetype.markers
    if not markers:
        return 0.0
    hit = sum(1 for m in markers if RULE_MARKER.format(tag=m) in skill_text)
    return round(hit / len(markers), 6)


def _record_for(episode: dict[str, Any], records: dict[str, Any] | None) -> Any:
    if not records:
        return None
    return records.get(str(episode.get("source_trace_id") or ""))


def deficient_markers_for_episodes(
    archetype: VerifierArchetype,
    episodes: list[dict[str, Any]],
    records: dict[str, Any] | None = None,
) -> dict[str, int]:
    """Count how often each marker is deficient across episodes (mining signal)."""
    counts: dict[str, int] = {m: 0 for m in archetype.markers}
    for episode in episodes:
        score = score_episode(archetype, episode, _record_for(episode, records))
        for marker in score.deficient_markers:
            counts[marker] = counts.get(marker, 0) + 1
    return counts


def evidence_strength(
    archetype: VerifierArchetype,
    episodes: list[dict[str, Any]],
    records: dict[str, Any] | None = None,
) -> float:
    """Mean contract completeness across episodes [0,1].

    High strength means the skill's traces already exhibit the contract (a clean
    positive prior); low strength flags a skill whose verifier would mostly mine
    deficiencies. Either way the archetype is *applicable*; this is a quality knob.
    """
    if not episodes:
        return 0.0
    total = sum(
        score_episode(archetype, e, _record_for(e, records)).contract_completeness
        for e in episodes
    )
    return round(total / len(episodes), 6)


SCORER_TEMPLATE = '''\
"""Self-contained deterministic scorer for verifier package {archetype_id}.

Generated by the OpenTraces Skill Verifier Factory. No imports beyond stdlib; safe
to run in default CI. Scores a candidate skill by the fraction of this archetype's
trace-grounded rule markers it addresses. Live/semantic legs are declared in
spec.yaml and are opt-in (never invoked here).
"""

from __future__ import annotations

ARCHETYPE_ID = {archetype_id!r}
SKILL_ID = {skill_id!r}
MARKERS = {markers!r}


def _marker_token(tag: str) -> str:
    return "rule[" + tag + "]"


def score_skill(skill_text: str) -> float:
    """Fraction of this archetype's markers the skill text addresses, in [0,1]."""
    if not MARKERS:
        return 0.0
    hit = sum(1 for m in MARKERS if _marker_token(m) in skill_text)
    return round(hit / len(MARKERS), 6)


if __name__ == "__main__":  # pragma: no cover
    import sys

    text = ""
    if len(sys.argv) > 1:
        with open(sys.argv[1], "r", encoding="utf-8") as fh:
            text = fh.read()
    print(score_skill(text))
'''


def render_scorer(
    archetype: VerifierArchetype, markers: tuple[str, ...] | None = None
) -> str:
    """Render the self-contained per-package ``scorer.py`` source.

    ``markers`` defaults to the full archetype contract; packagers pass the
    package's *addressable* (enforced) marker set so the shipped scorer matches
    the deterministic grader's ``required_markers`` and the Dsel/Dtest gate.
    """
    enforced = list(markers) if markers is not None else list(archetype.markers)
    return SCORER_TEMPLATE.format(
        archetype_id=archetype.archetype_id,
        skill_id=archetype.skill,
        markers=enforced,
    )
